create table if not exists public.compounds (
  id bigint generated by default as identity primary key,
  trivial_name text not null,
  iupac_name text,
  molecular_formula text,
  smiles text,
  inchi text,
  inchikey text,
  compound_class text,
  compound_subclass text,
  source_category text,
  source_organism text,
  source_material text,
  sample_code text,
  collection_location text,
  gps_coordinates text,
  depth_m double precision,
  uv_data text,
  ftir_data text,
  cd_data text,
  optical_rotation text,
  melting_point text,
  crystallization_method text,
  structure_image_path text,
  journal_name text,
  article_title text,
  publication_year text,
  volume text,
  issue text,
  pages text,
  doi text,
  ccdc_number text,
  molecular_weight double precision,
  hrms_data text,
  data_source text,
  note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.proton_nmr (
  id bigint generated by default as identity primary key,
  compound_id bigint not null references public.compounds(id) on delete cascade,
  delta_ppm double precision not null,
  multiplicity text,
  j_value text,
  proton_count text,
  assignment text,
  solvent text,
  instrument_mhz double precision,
  note text
);

create table if not exists public.carbon_nmr (
  id bigint generated by default as identity primary key,
  compound_id bigint not null references public.compounds(id) on delete cascade,
  delta_ppm double precision not null,
  carbon_type text,
  assignment text,
  solvent text,
  instrument_mhz double precision,
  note text
);

create table if not exists public.spectra_files (
  id bigint generated by default as identity primary key,
  compound_id bigint not null references public.compounds(id) on delete cascade,
  spectrum_type text not null,
  file_path text not null,
  note text
);

create table if not exists public.bioactivity_records (
  id bigint generated by default as identity primary key,
  compound_id bigint not null references public.compounds(id) on delete cascade,
  activity_label text not null,
  target_name text,
  target_category text,
  assay_type text,
  potency_type text,
  potency_relation text,
  potency_value double precision,
  potency_unit text,
  outcome text,
  assay_medium text,
  selectivity text,
  assay_source text,
  note text
);

create index if not exists idx_compounds_trivial_name on public.compounds(trivial_name);
create index if not exists idx_compounds_sample_code on public.compounds(sample_code);
create index if not exists idx_compounds_doi on public.compounds(doi);
create index if not exists idx_compounds_inchikey on public.compounds(inchikey);
create index if not exists idx_compounds_smiles on public.compounds(smiles);
create index if not exists idx_proton_compound on public.proton_nmr(compound_id);
create index if not exists idx_carbon_compound on public.carbon_nmr(compound_id);
create index if not exists idx_spectra_compound on public.spectra_files(compound_id);
create index if not exists idx_bioactivity_compound on public.bioactivity_records(compound_id);
create index if not exists idx_bioactivity_target_category on public.bioactivity_records(target_category);

alter table public.compounds enable row level security;
alter table public.proton_nmr enable row level security;
alter table public.carbon_nmr enable row level security;
alter table public.spectra_files enable row level security;
alter table public.bioactivity_records enable row level security;

drop policy if exists "viewer read compounds" on public.compounds;
create policy "viewer read compounds" on public.compounds for select using (true);

drop policy if exists "viewer read proton_nmr" on public.proton_nmr;
create policy "viewer read proton_nmr" on public.proton_nmr for select using (true);

drop policy if exists "viewer read carbon_nmr" on public.carbon_nmr;
create policy "viewer read carbon_nmr" on public.carbon_nmr for select using (true);

drop policy if exists "viewer read spectra_files" on public.spectra_files;
create policy "viewer read spectra_files" on public.spectra_files for select using (true);

drop policy if exists "viewer read bioactivity_records" on public.bioactivity_records;
create policy "viewer read bioactivity_records" on public.bioactivity_records for select using (true);

-- Write policies should be added only after auth is configured.
