alter table if exists public.compounds add column if not exists trivial_name text;
alter table if exists public.compounds add column if not exists iupac_name text;
alter table if exists public.compounds add column if not exists molecular_formula text;
alter table if exists public.compounds add column if not exists smiles text;
alter table if exists public.compounds add column if not exists inchi text;
alter table if exists public.compounds add column if not exists inchikey text;
alter table if exists public.compounds add column if not exists compound_class text;
alter table if exists public.compounds add column if not exists compound_subclass text;
alter table if exists public.compounds add column if not exists source_category text;
alter table if exists public.compounds add column if not exists source_organism text;
alter table if exists public.compounds add column if not exists source_material text;
alter table if exists public.compounds add column if not exists sample_code text;
alter table if exists public.compounds add column if not exists collection_location text;
alter table if exists public.compounds add column if not exists gps_coordinates text;
alter table if exists public.compounds add column if not exists depth_m double precision;
alter table if exists public.compounds add column if not exists uv_data text;
alter table if exists public.compounds add column if not exists ftir_data text;
alter table if exists public.compounds add column if not exists cd_data text;
alter table if exists public.compounds add column if not exists optical_rotation text;
alter table if exists public.compounds add column if not exists melting_point text;
alter table if exists public.compounds add column if not exists crystallization_method text;
alter table if exists public.compounds add column if not exists structure_image_path text;
alter table if exists public.compounds add column if not exists journal_name text;
alter table if exists public.compounds add column if not exists article_title text;
alter table if exists public.compounds add column if not exists publication_year text;
alter table if exists public.compounds add column if not exists volume text;
alter table if exists public.compounds add column if not exists issue text;
alter table if exists public.compounds add column if not exists pages text;
alter table if exists public.compounds add column if not exists doi text;
alter table if exists public.compounds add column if not exists ccdc_number text;
alter table if exists public.compounds add column if not exists molecular_weight double precision;
alter table if exists public.compounds add column if not exists hrms_data text;
alter table if exists public.compounds add column if not exists data_source text;
alter table if exists public.compounds add column if not exists note text;
alter table if exists public.compounds add column if not exists created_at timestamptz default now();
alter table if exists public.compounds add column if not exists updated_at timestamptz default now();

alter table if exists public.proton_nmr add column if not exists compound_id bigint;
alter table if exists public.proton_nmr add column if not exists delta_ppm double precision;
alter table if exists public.proton_nmr add column if not exists multiplicity text;
alter table if exists public.proton_nmr add column if not exists j_value text;
alter table if exists public.proton_nmr add column if not exists proton_count text;
alter table if exists public.proton_nmr add column if not exists assignment text;
alter table if exists public.proton_nmr add column if not exists solvent text;
alter table if exists public.proton_nmr add column if not exists instrument_mhz double precision;
alter table if exists public.proton_nmr add column if not exists note text;

alter table if exists public.carbon_nmr add column if not exists compound_id bigint;
alter table if exists public.carbon_nmr add column if not exists delta_ppm double precision;
alter table if exists public.carbon_nmr add column if not exists carbon_type text;
alter table if exists public.carbon_nmr add column if not exists assignment text;
alter table if exists public.carbon_nmr add column if not exists solvent text;
alter table if exists public.carbon_nmr add column if not exists instrument_mhz double precision;
alter table if exists public.carbon_nmr add column if not exists note text;

alter table if exists public.spectra_files add column if not exists compound_id bigint;
alter table if exists public.spectra_files add column if not exists spectrum_type text;
alter table if exists public.spectra_files add column if not exists file_path text;
alter table if exists public.spectra_files add column if not exists note text;

alter table if exists public.bioactivity_records add column if not exists compound_id bigint;
alter table if exists public.bioactivity_records add column if not exists activity_label text;
alter table if exists public.bioactivity_records add column if not exists target_name text;
alter table if exists public.bioactivity_records add column if not exists target_category text;
alter table if exists public.bioactivity_records add column if not exists assay_type text;
alter table if exists public.bioactivity_records add column if not exists potency_type text;
alter table if exists public.bioactivity_records add column if not exists potency_relation text;
alter table if exists public.bioactivity_records add column if not exists potency_value double precision;
alter table if exists public.bioactivity_records add column if not exists potency_unit text;
alter table if exists public.bioactivity_records add column if not exists outcome text;
alter table if exists public.bioactivity_records add column if not exists assay_medium text;
alter table if exists public.bioactivity_records add column if not exists selectivity text;
alter table if exists public.bioactivity_records add column if not exists assay_source text;
alter table if exists public.bioactivity_records add column if not exists note text;

create index if not exists idx_compounds_trivial_name on public.compounds(trivial_name);
create index if not exists idx_compounds_sample_code on public.compounds(sample_code);
create index if not exists idx_compounds_doi on public.compounds(doi);
create index if not exists idx_compounds_inchikey on public.compounds(inchikey);
create index if not exists idx_compounds_smiles on public.compounds(smiles);
create index if not exists idx_proton_compound on public.proton_nmr(compound_id);
create index if not exists idx_carbon_compound on public.carbon_nmr(compound_id);
create index if not exists idx_spectra_compound on public.spectra_files(compound_id);
create index if not exists idx_bioactivity_compound on public.bioactivity_records(compound_id);
create index if not exists idx_bioactivity_target_category on public.bioactivity_records(target_category);
