create table if not exists public.compounds (
    id bigint generated by default as identity primary key,
    trivial_name text not null,
    iupac_name text,
    molecular_formula text,
    source_material text,
    uv_data text,
    ftir_data text,
    optical_rotation text,
    melting_point text,
    crystallization_method text,
    structure_image_path text,
    note text,
    collection_location text,
    depth_m double precision,
    gps_coordinates text,
    sample_code text,
    compound_class text,
    compound_subclass text,
    journal_name text,
    publication_year text,
    volume text,
    pages text,
    doi text,
    data_source text,
    issue text,
    ccdc_number text,
    molecular_weight double precision,
    hrms_data text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    article_title text,
    smiles text,
    inchi text,
    inchikey text
);

create table if not exists public.proton_nmr (
    id bigint generated by default as identity primary key,
    compound_id bigint not null references public.compounds(id) on delete cascade,
    delta_ppm double precision not null,
    multiplicity text,
    j_value text,
    proton_count text,
    assignment text,
    solvent text,
    instrument_mhz double precision,
    note text
);

create table if not exists public.carbon_nmr (
    id bigint generated by default as identity primary key,
    compound_id bigint not null references public.compounds(id) on delete cascade,
    delta_ppm double precision not null,
    carbon_type text,
    assignment text,
    solvent text,
    instrument_mhz double precision,
    note text
);

create table if not exists public.spectra_files (
    id bigint generated by default as identity primary key,
    compound_id bigint not null references public.compounds(id) on delete cascade,
    spectrum_type text not null,
    file_path text not null,
    note text
);

create index if not exists idx_compounds_trivial_name on public.compounds(trivial_name);
create index if not exists idx_compounds_sample_code on public.compounds(sample_code);
create index if not exists idx_compounds_doi on public.compounds(doi);
create index if not exists idx_compounds_inchikey on public.compounds(inchikey);
create index if not exists idx_compounds_smiles on public.compounds(smiles);
create index if not exists idx_proton_compound on public.proton_nmr(compound_id);
create index if not exists idx_carbon_compound on public.carbon_nmr(compound_id);
create index if not exists idx_spectra_compound on public.spectra_files(compound_id);
